<a href="https://colab.research.google.com/github/SamillyNunes/machine-learning-study/blob/main/c_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# C-Means
O C-Means tem uma proposta semelhante ao K-Means, porem ele não associa uma instância de maneira absoluta a um cluster, ele faz uma atribuição de maneira **percentual**. Por exemplo, um elemento x pode pertencer 70% a o cluster 1 e 30% ao cluster 2.


In [ ]:
!pip install -U scikit-fuzzy # instalar o skfuzzy no collab

In [6]:
#imports
from sklearn import datasets
import numpy as np
from sklearn.metrics import confusion_matrix
import skfuzzy as fuzz 

In [7]:
iris = datasets.load_iris()

In [18]:
# Algoritmo definindo 3 clusters (c) e passando a matriz transposta (data.T). 
# Os demais params sao obrigatorios, e os valores passados sao os padroes
r = fuzz.cmeans(data=iris.data.T,c=3,m=2,error=0.005,maxiter=1000,init=None)

In [19]:
# obter a porcentagem de um registro pertencer ao cluster da posicao 1 na matriz:
previsoes_porcent = r[1]
previsoes_porcent

array([[9.96623638e-01, 9.75837576e-01, 9.79816172e-01, 9.67407621e-01,
        9.94469998e-01, 9.34542097e-01, 9.79481538e-01, 9.99546990e-01,
        9.30342033e-01, 9.82711667e-01, 9.68028349e-01, 9.92131559e-01,
        9.70623177e-01, 9.22935609e-01, 8.89722037e-01, 8.41292876e-01,
        9.46905525e-01, 9.96652279e-01, 9.04090381e-01, 9.79180795e-01,
        9.68584044e-01, 9.84826085e-01, 9.58644474e-01, 9.79409450e-01,
        9.66894371e-01, 9.73548308e-01, 9.94839985e-01, 9.93345325e-01,
        9.93673688e-01, 9.79502088e-01, 9.78712162e-01, 9.74349391e-01,
        9.38498153e-01, 9.04137140e-01, 9.85054705e-01, 9.84987701e-01,
        9.64169838e-01, 9.90889202e-01, 9.39653515e-01, 9.98288041e-01,
        9.94727422e-01, 8.50661030e-01, 9.52592441e-01, 9.79273589e-01,
        9.45238374e-01, 9.72128963e-01, 9.76782871e-01, 9.74207046e-01,
        9.77210888e-01, 9.97071338e-01, 4.45735579e-02, 2.92012316e-02,
        3.12533678e-02, 4.92331296e-02, 2.41467407e-02, 5.734732

In [20]:
# visualizar as porcentagens de um registro pertencer a cada cluster. Obs.: A soma é 1=100%
for x in range(150): # pq tem-se 150 instancias agrupadas
  print(previsoes_porcent[0][x], previsoes_porcent[1][x], previsoes_porcent[2][x])

0.9966236376329867 0.0023044473548637463 0.0010719150121496035
0.9758375760143013 0.016660738616267285 0.007501685369431533
0.9798161716304689 0.013766834030267268 0.006416994339263717
0.9674076205494766 0.022479943338596944 0.010112436111926557
0.9944699984363005 0.003762114217856113 0.001767887345843467
0.9345420970128578 0.04482968434400983 0.020628218643132485
0.9794815375128795 0.01401140482958282 0.006507057657537746
0.999546990411132 0.0003117352240281795 0.00014127436483980194
0.9303420329973899 0.04774627420800383 0.021911692794606436
0.9827116670110193 0.011943935868335441 0.0053443971206453365
0.9680283492384021 0.021767081849126943 0.010204568912471169
0.9921315586557423 0.005435934068460859 0.002432507275796744
0.970623176658922 0.020195443579298502 0.009181379761779554
0.9229356088672113 0.05181962403337578 0.02524476709941283
0.8897220365374798 0.07263521556553683 0.03764274789698333
0.8412928763704711 0.10438456558272108 0.05432255804680777
0.9469055250796393 0.03559342

In [21]:
# fazendo a previsao pegando a maior porcentagem de cada linha
previsoes = previsoes_porcent.argmax(axis=0)
previsoes

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1])

In [22]:
confusao = confusion_matrix(iris.target,previsoes)
confusao

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0, 13, 37]])